services:
  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${ASUSTORE_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${ASUSTORE_MINIO_ROOT_PASSWORD}
      MINIO_DOMAIN: ${ASUSTORE_MINIO_DOMAIN}
      MINIO_DEFAULT_BUCKETS: ${ASUSTORE_MINIO_BUCKETS}
    user: "0:0"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /volume1/Docker/minio/data:/data
    command: minio server /data --console-address ':9001'
#    entrypoint: >
#      /bin/sh -c "
#      minio server /data --console-address ':9001' &
#      tail -f /dev/null"
    networks:
      - intro-network

#  init:
#    image: minio/mc
#    depends_on:
#      - minio
#    entrypoint: /bin/sh
#    environment:
#      MINIO_BUCKET: ${MINIO_BUCKET}
#      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
#      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
#    command: >
#      -c "
#      while ! nc -z minio 9000; do echo 'Wait minio to startup...' && sleep 0.1; done;
#      sleep 5 &&
#      mc alias set myminio http://minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY &&
#      mc rm -r --force myminio/$MINIO_BUCKET || true &&
#      mc mb myminio/$MINIO_BUCKET &&
#      mc policy set download myminio/$MINIO_BUCKET
#      "
#    network_mode: "service:minio"

networks:
  intro-network: