services:
  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${ASUSTORE_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${ASUSTORE_MINIO_ROOT_PASSWORD}
      MINIO_DOMAIN: ${ASUSTORE_MINIO_DOMAIN}
    user: "0:0"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /volume1/Docker/minio/data:/data
    entrypoint: >
      /bin/sh -c "
      #!/bin/sh
        set -e
        
        log() {
        echo "$(date +"%Y-%m-%d %H:%M:%S") [INFO] $1"
      }
        
        error_log() {
        echo "$(date +"%Y-%m-%d %H:%M:%S") [ERROR] $1"
      }
        
        MAX_RETRIES=${MAX_RETRIES:-10}
        RETRY_INTERVAL=${RETRY_INTERVAL:-2}
        
        if [ "$DEBUG" = "true" ]; then
        set -x
        fi
        
        if [ -z "$MINIO_ROOT_USER" ] || [ -z "$MINIO_ROOT_PASSWORD" ]; then
        error_log "MINIO_ROOT_USER and MINIO_ROOT_PASSWORD must be set. Exiting..."
        exit 1
        fi
        
        start_minio() {
        log "Starting MinIO server..."
        minio server /data --console-address ':9001' &
      }
        
        wait_for_minio() {
        log "Waiting for MinIO to initialize..."
        sleep 5
      }
        
        configure_mc_alias() {
        retries=0
        log "Configuring mc alias..."
        until mc alias set myminio http://localhost:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do
        retries=$((retries+1))
        if [ $retries -ge $MAX_RETRIES ]; then
        error_log "Failed to configure mc alias after $MAX_RETRIES attempts. Exiting..."
        exit 1
        fi
        log "Retrying mc alias configuration ($retries/$MAX_RETRIES)..."
        sleep $RETRY_INTERVAL
        done
        log "mc alias configured successfully."
      }
        
        create_bucket() {
        bucket_name=$1
        retries=0
      log "Creating bucket: $bucket_name"
        until mc mb myminio/$bucket_name; do
        retries=$((retries+1))
        if [ $retries -ge $MAX_RETRIES ]; then
        error_log "Failed to create bucket $bucket_name after $MAX_RETRIES attempts. Exiting..."
        exit 1
        fi
        log "Retrying bucket creation ($bucket_name) ($retries/$MAX_RETRIES)..."
        sleep $RETRY_INTERVAL
        done
        log "Bucket $bucket_name created successfully."
      }
        
        trap "log 'Shutting down MinIO...'; pkill minio; exit 0" SIGTERM SIGINT
        
        start_minio
        wait_for_minio
        configure_mc_alias
        create_bucket "datalake"
        create_bucket "warehouse"
        
        log "MinIO is running. Waiting for termination signal..."
        wait

      tail -f /dev/null"
    networks:
      - intro-network

networks:
  intro-network: