services:
  traefik:
    image: traefik:v3.2.3
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "8080:8080" # Traefik Dashboard
      - "8082:8082" # Ping endpoint
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/Docker/traefik/acme.json:/acme.json
      - /volume1/Docker/traefik/config:/etc/traefik
    command:
      - "--api.insecure=true"  # Enable dashboard without auth - change in production
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.watch=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--ping=true"
      - "--ping.entrypoint=ping"
      - "--entrypoints.ping.address=:8082"
      - "--providers.docker.network=intro-network"
      # HTTPS Configuration
      - "--certificatesresolvers.letsencrypt.acme.email=josh.magady@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.httpChallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      # HTTP to HTTPS redirect
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    networks:
      - intro-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:8082/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      # Define middlewares
      - "traefik.enable=true"
      - "traefik.http.middlewares.ip-whitelist.ipwhitelist.sourcerange=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
      - "traefik.http.middlewares.acme-whitelist.ipwhitelist.sourcerange=0.0.0.0/0"

      # ACME challenge routing
#      - "traefik.http.routers.acme.rule=PathPrefix(`/.well-known/acme-challenge/`)"
#      - "traefik.http.routers.acme.entrypoints=web"
#      - "traefik.http.routers.acme.middlewares=acme-whitelist@docker"
#      - "traefik.http.routers.acme.priority=100"

      # Secure the dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.flowloom.com`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.middlewares=ip-whitelist@docker"

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${LH_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${LH_MINIO_ROOT_PASSWORD}
      MINIO_DOMAIN: ${LH_MINIO_DOMAIN}
      MINIO_DEFAULT_BUCKETS: ${LH_MINIO_BUCKETS}
      MINIO_BROWSER_REDIRECT_URL: https://minio.flowloom.com
      MINIO_SERVER_URL: https://minio.flowloom.com
    user: "0:0"
    volumes:
      - /volume1/Docker/minio/data:/data
      - /volume1/Docker/minio/config:/root/.minio
    command: minio server /data --console-address ':${LH_MINIO_CONSOLE_PORT:-9001}' --address ':${LH_MINIO_API_PORT:-9000}'
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s
    networks:
      - intro-network
    deploy:
      resources:
        limits:
          memory: ${LH_MINIO_MEMORY_LIMIT:-2g}
        reservations:
          memory: ${LH_MINIO_MEMORY_RESERVATION:-1g}
    labels:
      - "traefik.enable=true"
      # API
      - "traefik.http.routers.minio-api.entrypoints=websecure"
      - "traefik.http.routers.minio-api.rule=Host(`minio.flowloom.com`)"
      - "traefik.http.routers.minio-api.tls=true"
      - "traefik.http.routers.minio-api.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.minio-api.middlewares=ip-whitelist@docker"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"
      - "traefik.http.services.minio-api.loadbalancer.passHostHeader=true"
      # Console
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.rule=Host(`minio-console.flowloom.com`)"
      - "traefik.http.routers.minio-console.tls=true"
      - "traefik.http.routers.minio-console.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.minio-console.middlewares=ip-whitelist@docker"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      - "traefik.http.services.minio-console.loadbalancer.passHostHeader=true"

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: /bin/bash
    environment:
      MINIO_BUCKETS: ${LH_MINIO_DEFAULT_BUCKETS}
      MINIO_ACCESS_KEY: ${LH_MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${LH_MINIO_ROOT_PASSWORD}
      BUCKET_VERSIONING: ${LH_MINIO_BUCKET_VERSIONING:-false}
      BUCKET_PUBLIC_ACCESS: ${LH_MINIO_BUCKET_PUBLIC_ACCESS:-false}
      MAX_RETRY_ATTEMPTS: ${LH_MINIO_INIT_MAX_RETRIES:-30}
      RETRY_INTERVAL: ${LH_MINIO_INIT_RETRY_INTERVAL:-2}
    command: >
      -c "
      echo ""Buckets: $$MINIO_BUCKETS"";
      echo 'Check if MinIO is up';
      until mc alias set myminio http://minio:9000 $$MINIO_ACCESS_KEY $$MINIO_SECRET_KEY; do
        echo 'Waiting for MinIO to start...' && sleep 0.1;
      done;
      sleep 5;
      if [ -z \"$$MINIO_BUCKETS\" ]; then
        echo 'No buckets defined in MINIO_BUCKETS';
        exit 1;
      fi;
      IFS=',' read -ra BUCKETS <<< \"$$MINIO_BUCKETS\";
      for BUCKET in \"\$${BUCKETS[@]}\"; do
        echo \"Processing bucket: $$BUCKET\";
        if ! mc ls myminio/\$$BUCKET > /dev/null 2>&1; then
          mc mb myminio/\$$BUCKET;
        else
          echo \"Bucket \$$BUCKET already exists, skipping creation.\";
        fi;
      done;
      echo 'Bucket creation complete';
      echo 'MinIO initialization complete';
      "
    network_mode: "service:minio"

  nessie:
    image: bitnami/nessie:0.101.3
    container_name: nessie
    restart: unless-stopped
    user: "0:0"
    depends_on:
      minio:
        condition: service_healthy
    environment:
      QUARKUS_PROFILE: ${LH_NESSIE_QUARKUS_PROFILE}
      QUARKUS_HTTP_PORT: ${LH_NESSIE_API_PORT}
      QUARKUS_LOG_LEVEL: ${LH_NESSIE_LOG_LEVEL}
      OTEL_TRACES_EXPORTER: ${LH_NESSIE_OTEL_TRACES_EXPORTER}
      QUARKUS_OIDC_ENABLED: ${LH_NESSIE_OIDC_ENABLED}
      nessie.version.store.type: ROCKSDB
      nessie.version.store.persist.rocks.database-path: /nessie/db
    volumes:
      - /volume1/Docker/nessie/data:/nessie/data
      - /volume1/Docker/nessie/db:/nessie/db
    networks:
      - intro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/q/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nessie.entrypoints=websecure"
      - "traefik.http.routers.nessie.rule=Host(`nessie.flowloom.com`)"
      - "traefik.http.routers.nessie.tls=true"
      - "traefik.http.routers.nessie.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nessie.middlewares=ip-whitelist@docker"
      - "traefik.http.services.nessie.loadbalancer.server.port=19120"
      - "traefik.http.services.nessie.loadbalancer.passHostHeader=true"

  dremio:
    image: dremio/dremio-oss:25.2
    container_name: dremio
    restart: unless-stopped
    user: "0:0"
    environment:
      - DREMIO_MAX_HEAP_MEMORY_SIZE_MB=4096
      - DREMIO_MIN_HEAP_MEMORY_SIZE_MB=2048
      - DREMIO_MAX_DIRECT_MEMORY_SIZE_MB=8192
      - DREMIO_LOG_LEVEL=INFO
      - DREMIO_MAX_MEMORY_SIZE_MB=16384
      - DREMIO_GC_OPTS=-XX:+UseG1GC -XX:G1HeapRegionSize=32M
      - DREMIO_HOST=0.0.0.0
      - DREMIO_HTTP_PORT=${LH_DREMIO_CLIENT_ENDPOINT_PORT:-9047}
      - DREMIO_CLIENT_PORT=${LH_DREMIO_ALT_CLIENT_ENDPOINT_PORT:-31010}
      - DREMIO_ENABLE_TLS=false
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    volumes:
      - /volume1/Docker/dremio/data:/opt/dremio/data
    networks:
      - intro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9047/apiv2/server_status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      # Web UI
      - "traefik.http.routers.dremio.entrypoints=websecure"
      - "traefik.http.routers.dremio.rule=Host(`dremio.flowloom.com`)"
      - "traefik.http.routers.dremio.tls=true"
      - "traefik.http.routers.dremio.tls.certresolver=myresolver"
      - "traefik.http.routers.dremio.middlewares=ip-whitelist@docker"
      - "traefik.http.services.dremio.loadbalancer.server.port=9047"
      - "traefik.http.services.dremio.loadbalancer.passHostHeader=true"
      # Client Port (ODBC/JDBC)
      - "traefik.tcp.routers.dremio-client.entrypoints=dremio-client"
      - "traefik.tcp.routers.dremio-client.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.dremio-client.service=dremio-client"
      - "traefik.tcp.services.dremio-client.loadbalancer.server.port=31010"

  n8n:
    image: n8nio/n8n:1.73.1
    container_name: n8n
    restart: unless-stopped
    environment:
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_SECURE_COOKIE=true
      - N8N_WEBHOOK_URL=https://n8n.flowloom.com
      - WEBHOOK_URL=https://n8n.flowloom.com
      - N8N_ENDPOINT_REST=rest
      - N8N_ENDPOINT_WEBHOOK=webhook
      - N8N_ENDPOINT_WEBHOOK_TEST=webhook-test
      - N8N_PROTOCOL=https
      - N8N_PORT=80
      - N8N_PROXY_HOPS=1
    volumes:
      - /volume1/Docker/n8n/data:/home/node/.n8n
      - /volume1/Docker/n8n/files:/files
    user: "0:0"
    networks:
      - intro-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:80/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.rule=Host(`n8n.flowloom.com`)"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      # Custom headers and timeouts
      - "traefik.http.middlewares.n8n-websecure-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
#      - "traefik.http.middlewares.n8n-timeouts.forwardauth.requestTimeout=300"
#      - "traefik.http.routers.n8n.middlewares=ip-whitelist@docker,n8n-websecure-headers@docker,n8n-timeouts@docker"
      - "traefik.http.services.n8n.loadbalancer.server.port=80"
      - "traefik.http.services.n8n.loadbalancer.passHostHeader=true"

networks:
  intro-network:
    name: intro-network